PUT  http://localhost:8080/events/2
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTcwMzA2NTgzNCwidXNlcklkIjoyfQ.ckGYmRT42TIge0W9znpkY2m3BRdI_FOtZmQZZcslnOI

{
  "name": "Update Test event",
  "description": "A updated test event",
  "location": "A updated location ",
  "dateTime": "2025-01-01T15:30:00.000Z"
}